sudo: false
language: go
go:
  # - 1.6.x: bad for Redis 
  # - 1.7.x: bad for MySQL
  # - 1.8.x: bad for MySQL
  # - 1.9.x: bad for MySQL
  - 1.10.x
  - 1.11.x
  - 1.12.x

script: go test -v -cover -race
